#!/bin/sh

# Autostart
$HOME/.config/bspwm/autostart.sh

# Colors
mauve='#cba6f7'
red='#f38ba8'
blue='#89b4fa'
lavender='#b4befe'
surface1='#45475a'

#default monitor
if xrandr | grep "VGA-1 connected"; then
    Monitor='VGA-1'
    Monitor2='eDP-1'
    bspc monitor $Monitor -d I II III IV V VI VII VIII IX
    bspc monitor $Monitor2 -d X
    
else
  Monitor='eDP-1'
  bspc monitor $Monitor -d I II III IV V VI VII VIII IX

fi


#bspc monitor VGA-1 -d I II III IV V VI VII VIII IX
#bspc monitor eDP-1 -d X

bspc config border_width          3
bspc config normal_border_color   $surface1
bspc config focused_border_color  $blue
bspc config window_gap            12
bspc config -m $Monitor top_padding  35
bspc config -m $Monitor2 top_padding  0
bspc config split_ratio          0.50
bspc config borderless_monocle   true # remove the borders if the focused window is fullscreen
bspc config gapless_monocle      true # remove the gaps (spaces) between the windows if the focused window is fs
bspc config automatic_scheme     alternate

# Preselect
bspc config presel_feedback_color $blue

# Cursor
bspc config focus_follows_pointer true # the focus follow the cursor
bspc config pointer_follows_focus true # the cursor follow the focused window


# bspc rule -a "Virtual Machine Manager" desktop='^6' state=tiled follow=on
bspc rule -a Nitrogen state=floating
bspc rule -a Munadi state=floating
bspc rule -a Zathura state=tiled
bspc rule -a mpv desktop='IV' state=fullscreen follow=on
bspc rule -a Keepassxc desktop='VII' state=fullscreen 
bspc rule -a discord desktop='III' state=fullscreen follow=on
bspc rule -a gnome-calculator state=floating 
bspc rule -a Onboard state=floating 
bspc rule -a Com.gitlab.bitseater.meteo state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a amberol state=floating
bspc rule -a timer.py state=floating
bspc rule -a io.gitlab.idevecore.Pomodoro state=floating
bspc rule -a *:*:float99 state=floating
bspc rule -a float99 state=floating
bspc rule -a dialect state=floating
bspc rule -a calibre desktop='VI' follow=on
bspc rule -a Zathura desktop='IV' follow=on
